FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY ./custom-response-professores.json /usr/share/nginx/html/api/professores.json
COPY ./custom-response-turmas.json /usr/share/nginx/html/api/turmas.json

EXPOSE 80