services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: escola-app
    restart: always
    expose:
      - "3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=escola_infantil
    networks:
      - escola-network

  db:
    image: mysql:8.0
    container_name: escola-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=escola_infantil
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - escola-network
      
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: escola-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - escola-network

networks:
  escola-network:
    driver: bridge

volumes:
  db-data: