FROM nginx:alpine

# Copiar configuração personalizada do nginx
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Expor porta 80
EXPOSE 80

# Comando padrão do nginx
CMD ["nginx", "-g", "daemon off;"]